framework:
    messenger:
        transports:
            # Pas de file d'attente, on envoie les messages directement
            sync: 'sync://'

        routing:
            # On route les messages d'envoi d'email via le transport synchronisé
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': sync